server:
  port: 9000
spring:
  profiles:
    active: dev  # 环境标识，对应配置文件的环境后缀
  application:
    name: wbalone  # 应用名，对应配置文件的前缀
  # 核心：声明引入Nacos配置源（Spring Cloud Alibaba 2023.x+必填）
  config:
    import:
      - nacos:wbalone-${spring.profiles.active}.properties  # 应用自身配置（wbalone-dev.properties）
      - nacos:common.properties?group=common

  cloud:
    nacos:
      # 服务注册发现配置（可选，若需注册服务）
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos Server地址
        namespace: dev  # 命名空间（环境隔离）
        group: wbalone  # 配置分组
      # Nacos配置中心核心配置
      config:
        server-addr: 127.0.0.1:8848  # 与注册中心地址一致（可不同）
        namespace: dev  # 与共享配置的命名空间一致
        group: wbalone
        file-extension: properties  # 配置文件格式（properties/yaml）