server:
  port: 9000
spring:
  # 核心：声明引入Nacos配置源（Spring Cloud Alibaba 2023.x+必填）
  config:
    import:
      - nacos:wbalone-${spring.profiles.active}.properties  # 应用自身配置（wbalone-dev.properties）
      - nacos:common.properties?group=common
      - nacos:db.properties?group=common

  cloud:
    nacos:
      # 服务注册发现配置（可选，若需注册服务）
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848  # Nacos Server地址
        namespace: dev  # 命名空间（环境隔离）
        group: wbalone  # 配置分组
      # Nacos配置中心核心配置
      config:
        enabled: true
        server-addr:  ${spring.cloud.nacos.discovery.server-addr}  # 与注册中心地址一致（可不同）
        namespace: ${spring.cloud.nacos.discovery.namespace}  # 与共享配置的命名空间一致
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: properties  # 配置文件格式（properties/yaml）
        refresh: true

  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.108.227.234:3306/lirui_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: lirui
#    password: Sxyh_96968

# MyBatis-Plus配置
#mybatis-plus:
#  type-aliases-package: com.wbalone.mapper
#  mapper-locations: classpath*:/mybatis/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false