server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    name: wbalone

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: common
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: common