server:
  port: 9002 # 网关端口，与其他服务端口区分
spring:
  main:
    web-application-type: reactive
  gateway:
    routes:
      - id: wbalone-system
        uri: lb://wbalone-system
        predicates:
          - Path=/api/system/**
        filters:
          - StripPrefix=2
